<?php

/**
 * ShootProof API
 * This is documentation for a simple photo upload and management web application.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: john@johnplaxco.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class GalleryApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addGallery
     *
     * Creates a new gallery.
     *
     *
     * @return Http response
     */
    public function addGallery()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addGallery');
        }
        $body = $input['body'];


        return response('How about implementing addGallery as a post method ?');
    }
    /**
     * Operation deleteGallery
     *
     * Deletes a gallery..
     *
     * @param string $gallery_uuid Gallery UUID to delete (required)
     *
     * @return Http response
     */
    public function deleteGallery($gallery_uuid)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteGallery as a delete method ?');
    }
}
